### PR TITLE
Support Bundler 2.x

### PR DESCRIPTION
**Pull request by saturnflyer**
This addresses #36 

These changes also remove `File.exists?` to replace them with `File.exist?`

And this removes and ignores the Gemfile.lock 
- https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

### CODE REVIEW

**Comment by CHTJonas** [comment]
Would someone from @appfolio be able to take a look at this and possibly merge/cut a release?

**Comment by dvicory** [comment]
This looks good! We use gemsurance a few places internally so I'm checking with others if this is something we can do. Would it be possible to open up the dependencies to allow bundler `~> 1.2` or `~> 2.0` as well as rake `0.9.2.2` or `>= 10.0`?

**Comment by dvicory** [comment]
@saturnflyer So I followed up with some other people and confirmed we'd need to open up the dependencies to allow both the older and newer versions of bundler and rake. Once we have that, I'll be happy to merge and get a release out.

**Comment by saturnflyer** [comment]
@dvicory can the development dependencies just be moved to the Gemfile? I don't see a reason they need to be in the gemspec.

**Comment by dvicory** [comment]
> @dvicory can the development dependencies just be moved to the Gemfile? I don't see a reason they need to be in the gemspec.

I agree. Can you move the development dependencies as part of this PR?

**Comment by saturnflyer** [comment]
@dvicory done.

Looks like those dependencies could be updated but I'm not covering that in this PR

**Comment by dvicory** [comment]
Thank you! I'll work on getting a release cut with these changes as soon as possible.

**Pull request merged**
