### PR TITLE
Added a public method to the Runner class to build gems infos

### PR DESCRIPTION
**Pull request by bencolon**
Hi Jon, me again ;)

I've extracted gems infos build into a public method `build_gems_infos`, that sets an instance method `@bundled_gem_infos` (created and used by sub private methods) and returns it.

Thanks to this method, I'm writing a gemsurance_slack gem to send Gemsurance alerts in a Slack channel by calling `my_gems_infos = Gemsurance::Runner.new.build_gems_infos`.

Thx

### CODE REVIEW

**Comment by bencolon** [comment]
FYI [https://github.com/gatemedia/gemsurance_slack](https://github.com/gatemedia/gemsurance_slack)
Now using this PR source code.

**Comment by jonkessler** [comment]
I'm fine with making the gem infos publicly accessible, but I'd rather not pass them around in the Runner implicitly like this. I would much rather you just change the local variable to an instance variable in the run method and then add an attr_reader for the gem_infos.

**Comment by bencolon** [comment]
I can't do that because I don't want to have to call the current run method (which generate a report) to just set the gem_infos attribute.

What do you think about having 2 public methods : 
- `run` which only builds gem_infos,
- `report` which generates the report.

Something like that : 

```ruby
module Gemsurance
  class Runner
    attr_reader :gem_infos

    def initialize(options = {})
      @formatter   = options.delete(:formatter) || :html
      @output_file = options.delete(:output_file) || "gemsurance_report.#{@formatter}"
      @options     = options
    end

    def run
      build_gem_infos
      self # for methods chaining
    end

    def report
      generate_report
      exit 1 if @gem_infos.any? { |info| info.vulnerable? }
    end

  private
    def build_gem_infos
      @gem_infos = retrieve_bundled_gem_infos
      retrieve_vulnerability_data
      add_vulnerability_data
    end

    ...
```

So in the exec file : 
```ruby
Gemsurance::Runner.new(options).run.report
```
And for my gem : 
```ruby
my_gem_infos = Gemsurance::Runner.new(options).run.gem_infos
```

Thoughts ?

**Comment by jonkessler** [comment]
Hmm, that's a fair point. That's reasonable, but I think report needs to have a check to make sure that run has already been called.

**Comment by bencolon** [comment]
Hey Jon, could you please have a look to my update ?

**Comment by jonkessler** [comment]
Looks good.. I'm waiting for someone to enable travis for me, as this project is in my company's organization.

**Pull request merged**
