### PR TITLE
Fixed bug to run the tests

### PR DESCRIPTION
**Pull request by bencolon**
Added "test-unit" gem development dependency.

### CODE REVIEW

**Comment by jonkessler** [comment]
Sorry.. why is this necessary? The tests run fine locally for me.

**Comment by bencolon** [comment]
I guess you've already `test-unit`gem installed in your local gemset.
On master branch, try `gem uninstall test-unit`, then `bundle install`, then `rake test:units` ... bim `'require': cannot load such file -- test/unit (LoadError)`.
Now same with this PR, tests are running fine ;)

**Comment by jonkessler** [comment]
Ruby 2.1.5 actually won't let me uninstall test-unit.
[~/src/gems/gemsurance]$ gem uninstall test-unit                                                                                                             
ERROR:  While executing gem ... (Gem::InstallError)
    gem "test-unit" cannot be uninstalled because it is a default gem
Are you on a different Ruby version?

**Comment by bencolon** [comment]
Right, I'm using 2.2.0.
And it seems that Ruby 2.2 [removed](https://bugs.ruby-lang.org/issues/9711) 'test-unit' from stdlib, so everything is normal from your and my side ;).
What do you prefer ? Adding this `test-unit` gem dependency or a `.ruby-version` file (with 2.15) in the project ?

**Comment by jonkessler** [comment]
Ah, interesting. I'd be OK adding the dependency if it works in other ruby versions as well. I've actually been meaning to get travis set up for the repo. Let me look into that.

**Comment by jonkessler** [comment]
Thanks!

**Pull request merged**
